name: sparrow_utils
description: Sparrow Utils Library for Dart.
version: 0.1.0
homepage: https://github.com/sparrow-genius/sparrow_utils

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  enum_to_string: ^1.0.9
  intl: ^0.16.1

dev_dependencies:
  build_test: ^0.10.11
  test: ^1.15.0
