name: sparrow_utils
description: Sparrow Utils Library for Flutter.
version: 0.5.1
homepage: https://github.com/sparrow-frontend/sparrow_utils

environment:
  sdk: ">=2.7.0 <2.12.0"

dependencies:
  flutter:
    sdk: flutter
  enum_to_string: ^1.0.9
  flutter_screenutil: ^4.0.4+1
  intl: ^0.16.1
  time: ^1.4.1 #系统时间的增强扩展

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_test: ^1.3.6
  test: ^1.15.0
