name: sparrow_utils
description: Sparrow Utils Library for Flutter.
version: 0.8.2
homepage: https://github.com/sparrow-frontend/sparrow_utils

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  enum_to_string: ^2.0.1
  flutter_screenutil: ^5.0.0+2
  intl: ^0.17.0
  time: ^2.0.0 #系统时间的增强扩展

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_test: ^2.0.0
  test: ^1.16.5
